### ISSUE TITLE
What's the verification code?

### ISSUE THREAD

**Issue by KingPa0** [wilminator/dokuwiki-plugin-twofactor#10]
Hi,
First of all, thank you very much for this plugin and the incredible work you did!
I'm using it with Google Authenticator and it works fine.

The thing I don't understand is when I'm asked for my _Verification Code_ (see picture: https://s7.postimg.cc/txevgdy23/otp.png ).
It happens after a few hours without using the wiki. I tried to enter my Google tokens but I keep having this message. The only option is to log out and log in again.

Thanks !

**Comment by wilminator** [comment]
That's strange.  It would not be your Google token, that is for codes sent by SMS or email.  It may be a new feature of the more recent releases that I have not encountered yet.  I'm working on reviewing functionality with Greebo, hopefully fixing that will fix this.  If not, then we can look into this more.

**Comment by wilminator** [comment]
Thinking about this, the PHP session is what tracks that you have logged in with 2FA.  If the session file on the webserver was erased, then you'd lose that login.  If DokuWiki can retain your login using a cookie, then you'd end up in that scenario if you were only using Google Authenticator- you can't use tokens after you've logged in because we don't want to let a hacker guess your password and get confirmation by seeing the OTP code screen.

Give me some time to research this and figure out how to handle this issue.

**Comment by KingPa0** [comment]
Hi Michael,

Thank you for the explanation, it makes sense.
There is no emergency for this issue. Take the time you need and thank you for the work you already put in this extension! 

Le 20 juin 2018 08:29, à 08:29, Michael Wilmes <notifications@github.com> a écrit:

**Comment by wilminator** [comment]
Hello,
I have reviewed the DW source and my code, and faked the loss of the PHP session data and have the exact same symptom happening on my development box.  DW works around this by creating a cookie that can be used to log a user back in without a current session.   This enables a user to remain logged in for the life of the cookie and not the session.

I have put together a fix and pushed it out.  Based on my testing, the loss of the session will no longer kill your login if your cookies are still good.  Please let me know if this works.

**Comment by wilminator** [comment]
This is still not fixed.  I need to find a way to track a 2FA login if the session goes away completely.

**Comment by wilminator** [comment]
@ffito and @KingPa0 could you let me know which webserver and browser you are using?  You can respond to "michael dot wilmes at gmail dot com".

**Comment by KingPa0** [comment]
Hi @wilminator 
Your fix seems to work. I don't have the issue anymore! Thank you for that.
I'll email you the details tonight.

**Comment by wilminator** [comment]
@ffito, can you tell me which timeout you are referring to? The module is not supposed to cause the wiki to stay logged in.

**Comment by ffito** [comment]
@wilminator I'm not sure how it was done (I don't have access to server config), but our wiki used to end inactive sessions at the time specified under auth_security_timeout. Now it stays logged in unless I delete the cookies

**Comment by wilminator** [comment]
@ffito this module does not change the core wiki login system, so that might be another issue.  The only wiki setting I have seen that controls login time is the "rememberme" setting, which enables permanent cookie-based logins.  I suspect that if it was turned off, the user would be logged out after the browser is closed.

**Comment by wilminator** [comment]
By any chance, is anyone logging into multiple browsers simultaneously?

**Comment by wilminator** [comment]
I was finally able to replicate this on my computer.  Had to stop and eat :) . Anyway, I see what is happening and might have a valid solution.  I will post again when I've pushed code.

**Comment by KingPa0** [comment]
I do! I usually connect at home and at work (and even sometimes on my
phone).

2018-07-05 2:15 GMT+02:00 Michael Wilmes <notifications@github.com>:

> By any chance, is anyone logging into multiple browsers simultaneously?
>

**Comment by wilminator** [comment]
I have pushed out an update that should address this problem.  I had to rewrite the workflow to correct some additional problems, after I had already made a feature update.    I have spent the last few days testing and think this is ready.  Please update and let me know how it works for you.

**Comment by KingPa0** [comment]
I already tried twice but everytime I have this error:
Parse error: syntax error, unexpected 'const' (T_CONST), expecting 
variable (T_VARIABLE) in 
/home/MYUSERNAME/public_html/doku/lib/plugins/twofactor/action.php on 
line 919

Can't do anything except a restore...

Michael Wilmes a écrit:

**Comment by wilminator** [comment]
Sorry about that.  I did not realize that public and private constants for
classes were not added until PHP 7.1.  I'm releasing an update for this now.

**Comment by wilminator** [comment]
I also was notified of another similar PHP issue that I had to fix.  I have
just released that update.

**Comment by wilminator** [comment]
Closing due to no response.  No news is good news.

**Comment by KingPa0** [comment]
Sorry for the lack of response. I didn't use the wiki a lot theses days but this time it's working fine, thank you very much for all the work!

All the best,
KingPa0
