### ISSUE TITLE
Error Thrown when Accessing TwoFactor Admin and Using Active Directory Authentication

### ISSUE THREAD

**Issue by streaml1ne555** [wilminator/dokuwiki-plugin-twofactor#11]
I'm getting this stack trace when I use AD auth and the two-factor plugin on Greebo:

2018/06/26 15:19:34 [error] 27034#0: *5168 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getUserData() on null in /usr/local/www/dokuwiki/lib/plugins/twofactor/admin.php:394
Stack trace:
#0 /usr/local/www/dokuwiki/lib/plugins/twofactor/admin.php(405): admin_plugin_twofactor->_retrieveFilteredUsers(Array)
#1 /usr/local/www/dokuwiki/lib/plugins/twofactor/admin.php(159): admin_plugin_twofactor->_getUserCount(Array)
#2 /usr/local/www/dokuwiki/inc/Action/Admin.php(47): admin_plugin_twofactor->handle()
#3 /usr/local/www/dokuwiki/inc/ActionRouter.php(83): dokuwiki\Action\Admin->preProcess()
#4 /usr/local/www/dokuwiki/inc/ActionRouter.php(48): dokuwiki\ActionRouter->setupAction('admin')
#5 /usr/local/www/dokuwiki/inc/ActionRouter.php(60): dokuwiki\ActionRouter->__construct()
#6 /usr/local/www/dokuwiki/inc/actions.php(16): dokuwiki\ActionRouter::getInstance(true)
#7 /usr/local/www/dokuwiki/doku.php(120): act_dispatch()
#8 {main}

While setting up this wiki the TwoFactor Admin link would show up with no users despite having myself configured for 2FS with Google Authenticator. Now it's just showing a blank page with this trace in the error log.

**Comment by wilminator** [comment]
Hello,
Reviewing the error you sent me, it appears that the module is not able to get a reference to the AD authentication module you are using.  I never put in proper error handling for this, and that is why you are seeing that error.  I'm adding code to display the error the 2FA module had referencing the AD authentication module.

That said, my module has two requirements for using any authentication module: 1) it must be setup enough to initialize and 2) the module must have "getUsers" permission. For ADAuth, this permission is only present if you have defined both the admin_username and admin_password parameters.  While it says "admin", the account I used in my work environment was not a domain admin account; it was a basic user account with read permissions and was used exclusively to lookup usernames.  I recommend a dedicated account be used with a minimum 24 character random password.  Without this set, the module will not have getUsers access to the authentication system and will be unable to list users, and my module will be unable to function.

**Comment by streaml1ne555** [comment]
Late follow up. The admin account fixed this issue for me. I don't recall seeing this in the documentation. If it's not currently there it may be worthwhile to add. Thanks for the help!

**Comment by wilminator** [comment]
I have a rework that removes the need for the account.  The only side
effect is not seeing the user's email address, which is obtained through
the authentication plugin.  I will release that shortly; I'm working on
making it language friendly right now.
Mike

**Comment by wilminator** [comment]
I have released the rework.  If you would like to try using it, please let me know how well it works.  Otherwise please close this issue.  Thanks!
