### ISSUE TITLE
Extract error in admin page

### ISSUE THREAD

**Issue by wilminator** [wilminator/dokuwiki-plugin-twofactor#17]
@Draky50110 Reported an error in the admin page involving the extract command.

**Comment by wilminator** [comment]
@Draky50110 I think I have tracked down the problem.  I'm working on a fix.

**Comment by wilminator** [comment]
@Draky50110 An update is out. please check it out.  Also, the "1" user is the cause of the error you are seeing and a problem caused by my code creating a login cookie for unauthenticated users.  Feel free to purge that "user".

**Comment by Draky50110** [comment]
Purged the user, now all is ok :)
