### ISSUE TITLE
Error before login

### ISSUE THREAD

**Issue by Draky50110** [wilminator/dokuwiki-plugin-twofactor#18]
Hi.
Got an error on top of the page if not logged anymore by Dokuwiki.
Only happens if main cookie fro Dokuwiki is not login me because I didn't check the box at first screen.
If I login and disconnect, it did not happen.
Here is the screen : 
![2fa-login](https://user-images.githubusercontent.com/1558487/42923755-83fe7f34-8b27-11e8-896b-cae3ad06b34a.png)
As it is not blocking, it is not very important ;)

**Comment by wilminator** [comment]
If you would mind testing this change.  I can't replicate the issue on my end, so I'm hoping this works.
[array_fix.txt](https://github.com/wilminator/dokuwiki-plugin-twofactor/files/2212252/array_fix.txt)

**Comment by Draky50110** [comment]
As the error never came back... I didn't test.
You can commit it I think, if there is a problem, I'll let you know here ;)

**Comment by wilminator** [comment]
Released and closing.
