### ISSUE TITLE
"Two Factor Settings" item doesn't appear when using bootstrap3 template

### ISSUE THREAD

**Issue by hokkaidoperson** [wilminator/dokuwiki-plugin-twofactor#20]
"Two Factor Settings" item appears with default dokuwiki template, but doesn't appear when using bootstrap3 template.
Bootstrap3 template is one of the most popular template of DokuWiki, so I hope this plugin becomes compatible with it.

**Comment by hokkaidoperson** [comment]
I found that enabling "user" in tpl»bootstrap3»showIndividualTool activates "Two Factor Settings"

**Comment by wilminator** [comment]
Thank you!  I will update the plugin page with this news.
