### ISSUE TITLE
0 results in 2FA admin

### ISSUE THREAD

**Issue by tuudik** [wilminator/dokuwiki-plugin-twofactor#3]
Hi!

We have 4 users using GA 2FA.
I accidently deleted my own user 2FA code generation from my phone (fortunatly I have separate account).

Now when I want to reset for my personal user, I can't since it shows no results.

Any ideas?

**Comment by wilminator** [comment]
Hello,
You should be able to reset the two factor settings on the affected account if you log in as a wiki admin.  Navigate to the Admin page, then click the "TwoFactor Admin" link under the Additional Plugins header.  You should now see a list of all users that have tried to use the TwoFactor modules.  to erase any TwoFactor settings for a user, check the box next to their name and click "Reset Selected".  That should enable your other account to log in without the need for a login token or one time password.  Please let me know if this helped.
Greetings,
Mike
