### ISSUE TITLE
Installing the plugin returns syntax error

### ISSUE THREAD

**Issue by OHeinzen** [wilminator/dokuwiki-plugin-twofactor#5]
Hi there,
I'm trying to implement the core plugin on our server, but every time I do so, the site locks down and only returns "error code 500". I've turned to my admin and asked whether this had to do with security settings on the apache server. He provided me the error log, containing this:

[Thu Apr 14 14:31:39 2016] [error] [client 139.14.12.231] PHP Parse error:  syntax error, unexpected '[', expecting ']' in /media/nss/DATA/www/htdocs/biopsy/trojan/root/dokuwiki/lib/plugins/twofactor/action.php on line 662

Any ideas?

**Comment by milleiro** [comment]
Hi,

I'm with the same trouble. Did you work it out? How?

Thanks!

**Comment by wilminator** [comment]
I'm sorry - I didn't see this thread earlier.  I will try to see what I can find.

**Comment by wilminator** [comment]
The error stems from me using a shortcut to reference the first element of an array generated by a function (I think).  To eliminate that and help with future troubleshooting, I have updated the code to use placeholder variables.  Best case scenario, the problem goes away.  Worst case scenario, the errors reported become a little more specific.  I will release this in the next couple of days.

**Comment by juanmilleiro** [comment]
Thanks!



--

juan andrés milleiro

http://juanandres.milleiro.com





El Vie, 3 Mar, 2017, a las 07:51, Michael Wilmes escribió:

> The error stems from me using a shortcut to reference the first
> element of an array generated by a function (I think).  To eliminate
> that and help with future troubleshooting, I have updated the code to
> use placeholder variables.  Best case scenario, the problem goes away.
> Worst case scenario, the errors reported become a little more
> specific.  I will release this in the next couple of days.
> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/wilminator/dokuwiki-plugin-twofactor/issues/5#issuecomment-283880171

**Comment by wilminator** [comment]
I have refactored my code to save the function to a variable then access the index.  This has been committed.  Please let me know if there are any other outstanding issues.

**Comment by juanmilleiro** [comment]
Hi,



I activated again Google and Core plugin and as soon as I activate
Google after the Core plugin, it says...

Verification Code
Verification Code 




Resend OTP using all configured options



But I don't have nothing!



--

juan andrés milleiro

http://juanandres.milleiro.com





El Jue, 9 Mar, 2017, a las 07:19, Michael Wilmes escribió:

> I have refactored my code to save the function to a variable then
> access the index.  This has been committed.  Please let me know if
> there are any other outstanding issues.
> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/wilminator/dokuwiki-plugin-twofactor/issues/5#issuecomment-285265649
